spring.application.name=BaitapAPI

# JPA
spring.jpa.hibernate.ddl-auto=validate  # Thay update bằng validate để tránh thay đổi schema tự động
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect  # Cập nhật dialect
spring.jpa.properties.hibernate.format_sql=true

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ltweb1;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Server port
server.port=8090

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

storage.location=uploads